apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cyber-city-frontend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - safecommu.org
      secretName: safecommu-org-tls
  rules:
    - host: safecommu.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cyber-city-frontend
                port:
                  number: 80
