apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: safecommu

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: registry.cyber-safekids.com/safecommu/cyber-city-frontend
    newTag: "30"
